In [ ]:
"""
PROGRAMMING WITH PYTHON PROJECT
TOPIC -  PYBLAS 1
GROUP 8
GROUP MEMBERS :
    A ANUSHRUTH REDDY(UCSE21001)
    P SNEHA (UCSE21022)
    SAANVI SWAIN (UCSE21027)
    SHUBHAM DAS (UCSE21051)
    PRANGYA JENA (UCSE21059)
    
    
PRESENTED TO Dr.Chandan Misra

"""

In [7]:
pip install numpy pyblas

Note: you may need to restart the kernel to use updated packages.


In [2]:
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.abspath(''), "..", "..")))

In [22]:
import numpy as np
import math
import pyblas
from pyblas.level1 import dswap
from pyblas.level1 import dscal
from pyblas.level1 import dcopy
from pyblas.level1 import daxpy
from pyblas.level1 import ddot
from pyblas.level1 import dsdot
from pyblas.level1 import dnrm2
from pyblas.level1 import dznrm2
from pyblas.level1 import dasum

In [23]:
# DSWAP - Swaps the contents of a vector x with a vector y
x = np.array([1, 2, 3], dtype=np.double)
y = np.array([6, 7, 8], dtype=np.double)
N = len(x)
incx = 1
incy = 1
dswap(N, x, incx, y, incy)
print("x = ",x)
print("y = ",y)

x =  [6. 7. 8.]
y =  [1. 2. 3.]


In [24]:
#DSCAL - Scales a vector, x, by a constant alpha
x = np.array([1, 2, 3], dtype=np.double)
N = len(x)
alpha = 5
incx = 1
dscal(N, alpha, x, incx)
print(x)

[ 5. 10. 15.]


In [25]:
#DCOPY - Copies a vector, x, to a vector, y.
x = np.array([1, 2, 3], dtype=np.double)
y = np.array([6, 7, 8], dtype=np.double)
N = len(x)
incx = 1
incy = 1
dcopy(N, x, incx, y, incy)
print("y =", y)

y = [1. 2. 3.]


In [26]:
#DAXPY - Adds a vector x times a constant alpha to a vector y
x = np.array([1, 2, 3], dtype=np.double)
y = np.array([6, 7, 8], dtype=np.double)
N = len(x)
alpha = 5
incx = 1
daxpy(N, alpha, x, incx, y, incy)
print(y)

[11. 17. 23.]


In [27]:
#DDOT - Computes the dot-product of a vector x and a vector y.
x = np.array([1, 2, 3], dtype=np.double)
y = np.array([6, 7, 8], dtype=np.double)
N = len(x)
incx = 1
incy = 1
z = ddot(N, x, incx, y, incy)
print(z)

44.0


In [28]:
#DSDOT - Computes the dot-product of a vector x and a vector y.
x = np.array([1, 2, 3], dtype=np.single)
y = np.array([4, 5, 6], dtype=np.single)
N = len(x)
incx = 1
incy = 1
dsdot(N, x, incx, y,incy)

32.0

In [29]:
#DNRM2 - Computes the Euclidean norm of the vector x
x = np.array([1, 2, 3], dtype=np.double)
N = len(x)
incx = 1
print(dnrm2(N, x, incx))

3.7416573867739413


In [30]:
#DZNRM2 - Computes the Euclidean norm of the vector x
x = np.array([1+2j, 2+3j, 3+4j], dtype=np.complex64)
N = len(x)
incx = 1
print(dznrm2(N, x, incx))

6.5574384


In [31]:
#DASUM- Computes the sum of absolute values of elements of the vector x
X = np.array([1, 2, 3 , 4], dtype=np.double)
N = len(X)
incx = 1
s=dasum(N, X, incx)
print(s)

[1. 2. 3. 4.]
